# Generated by Django 5.2.11 on 2026-04-26 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['manager', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='ExpenseApp.userprofile'),
        ),
    ]
